# -*- coding: utf-8 -*-
"""IBM_Assn2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SIgVZ-4FrUoDNC9WOu71x4qGUNty_RLH
"""

import requests

s="https://api.openweathermap.org/data/2.5/weather?q=Chennai,IN&appid=5c3a4cc6799706c0ef54f8e06cdd1646"

min_temp= 30
max_temp=60

min_humidity= 30
max_humidity= 60

for i in range(100):
  r=requests.get(url=s)
  data=r.json()
  temp= data['main']['temp'] - 273
  humid=data['main']['humidity']

  print ("temperature is:", t)
  print ("Humidity is :", humid)

  if(temp < min_temp or temp > max_temp):
    print("Not a safe temperature,ALARM!!")

  if(humid < min_humidity or humid > max_humidity):
    print("Not a safe Humidity value, ALARAM!!")